spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:./config/config-server/configs/{application},file:/configs/{application}

server:
  port: 8888