server:
  port: 8086

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka-server:8761/eureka/
jwt:
  expiration-time: 3600000
  key-id: 3cfa76ef14937c1c0ea519f8fc #i know it shouldnt be here its just presentation