apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: jovan99djokic/eureka-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m" #We set here the java memory limit
        livenessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8761
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1