server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  activemq:
    broker-url: (tcp://localhost:61616,tcp://artemis-mq:61616)?randomize=false
    user: artemis
    password: artemis

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
