server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  activemq:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis

ecommerce-platform:
  jms:
    order-update-dest: order-update-dest