name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Verify with Maven
      run: |
        mvn -B package --file config/config-server/pom.xml
        mvn --batch-mode --update-snapshots -f config/config-server/pom.xml verify
        
    - name: Prepare JAR for Docker
      run: mkdir target && cp config/config-server/target/*.jar target
      
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: config-server-jar
        path: config/config-server/target/config-server-0.0.1-SNAPSHOT.jar



  dockerize:
    runs-on: ubuntu-latest
    needs: build_and_publish

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download the JAR artifact
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: config-server-jar
          path: target/

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t jovan99djokic/config-server:latest -f config/config-server/Dockerfile .

      # Log in to Docker Hub
      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push jovan99djokic/config-server:latest