name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: config-server
            path: config/config-server
          - name: eureka-server
            path: discovery/eureka-server
          - name: order-service
            path: services/order-service

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test to see if this is Services and build common models #Because i need to copy common-models into docker container to run service succesfully
        if: matrix.service.name == 'inventory-service' || 'order-service' || 'payment-service' || 'product-service' || 'user-service'
        run: |
          mvn -B package --file ${{ matrix.service.path }}/pom.xml
          mvn --batch-mode --update-snapshots -f ${{ matrix.service.path }}/pom.xml verify

      - name: Build and Verify with Maven
        run: |
          mvn -B package --file ${{ matrix.service.path }}/pom.xml
          mvn --batch-mode --update-snapshots -f ${{ matrix.service.path }}/pom.xml verify

      
      - name: Prepare JAR and Configs for Docker
        run: |
          mkdir -p deploy_artifact_${{ matrix.service.name }}
          cp ${{ matrix.service.path }}/target/*.jar deploy_artifact_${{ matrix.service.name }}/

      - name: Test to see if this is config-server
        if: matrix.service.name == 'config-server'  
        run: |
          cp -R ${{ matrix.service.path }}/configs deploy_artifact_${{ matrix.service.name }}/

      - name: Upload JAR and Configs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service.name }}-artifact
          path: deploy_artifact_${{ matrix.service.name }}



  dockerize:
    runs-on: ubuntu-latest
    needs: build_and_publish
    strategy:
      matrix:
        service:
          - name: config-server
            path: config/config-server
          - name: eureka-server
            path: discovery/eureka-server
          - name: order-service
            path: services/order-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.service.name }}-artifact
          path: deploy_artifact_${{ matrix.service.name }}

      
      - name: Prepare Docker Build Context
        run: |
          mkdir -p target  # Ensure target directory exists
          mv deploy_artifact_${{ matrix.service.name }}/*.jar ./target/

      - name: Test to see if this is config-server
        if: matrix.service.name == 'config-server'  
        run: |
          mv deploy_artifact_${{ matrix.service.name }}/configs .

      - name: List all files for debugging
        run: ls -R  

      
      - name: Build Docker Image
        run: |
          docker build -t jovan99djokic/${{ matrix.service.name }}:latest -f ${{ matrix.service.path }}/Dockerfile .

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push jovan99djokic/${{ matrix.service.name }}:latest
